Repository wikicensorship/tracevis, pull requests merged in 2022-06, with the labels that each got.

#58 feat: ability to set iface
  tracevis.py
  utils/geolocate.py
  utils/trace.py
Labels: bug, enhancement, priority/high

#59 slightly smaller docker image via Alpine Linux
  .dockerignore
  Dockerfile
  README.md
Labels: enhancement, priority/low

#61 feat: new argument to change port
  tracevis.py
  utils/trace.py
Labels: enhancement

#62 add legend
  utils/templates/template_main.html.jinja
  utils/templates/template_offline.html.jinja
  utils/vis.py
Labels: enhancement, priority/low

#63 feat: make it easier to use packet input
  utils/packet_input.py
Labels: enhancement, priority/medium

#66 feat: combine multiple json file
  tracevis.py
Labels: enhancement, priority/medium

#57 feature: unittests
  .github/workflows/unittest.yml
  .gitignore
  README.md
  requirements.txt
  test/__init__.py
  test/test_operationality.py
  tracevis.py
Labels: enhancement, priority/high

#70 fix: iptables existence
  tracevis.py
  utils/packet_input.py
Labels: bug, priority/high
